### ISSUE TITLE
could you update the example script?

### ISSUE THREAD

**Issue by anic** [angr/angr-doc#213] opened 2018-09-26 08:54 UTC
angr-doc/examples/csaw_wyvern/solve.py  is already fail to run by the latest angr version. could you update the example file so that we could learn how to use angr ?

error message as follow: 

Traceback (most recent call last):
  File "solve.py", line 52, in <module>
    print main()
  File "solve.py", line 21, in main
    k = st.posix.files[0].read_from(1)
AttributeError: 'SimSystemPosix' object has no attribute 'files'

**Comment by rhelmot** [comment] 2018-09-26 09:14
Duplicate of https://github.com/angr/angr/issues/1186

A fixed version is on another branch, linked from that issue. It will be merged within the next week. Backporting it now would just cause merge issues.

**Closed by rhelmot** 2018-09-26 09:14 UTC
