### ISSUE TITLE
SimMemoryAddressError

### ISSUE THREAD

**Issue by krar01** [angr/angr-doc#162] opened 2017-11-06 11:39 UTC
When I run this solve.py for onlyone.exe in layer7_onlyone is get the following: 
SimProcedure class is deprecated
angr.errors.SimMemoryAddressError: Unable to concretize address for load with the provided strategies.

**Comment by rhelmot** [comment] 2017-12-18 06:16
oh, looks like I missed this one, and now it's a duplicate of #164

**Closed by rhelmot** 2017-12-18 06:16 UTC
