### ISSUE TITLE
The problem about CFG

### ISSUE THREAD

**Issue by taozi-xx** [angr/angr-doc#267] opened 2019-05-16 02:23 UTC
An error occured  When I want to recover the control-flow graph of a binary program. How to resolve this problem？ And why is this problem happening？

```
File "/home/xx/Tools/pycharm_project/Call_Birthmark/import_exe_new.py", line 9, in import_exe
    cfg_fast = p.analyses.CFGFast(normalize=True)
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/cfg/cfg_fast.py", line 1013, in __init__
    self._analyze()
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/forward_analysis.py", line 552, in _analyze
    self._analysis_core_baremetal()
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/forward_analysis.py", line 653, in _analysis_core_baremetal
    self._job_queue_empty()
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/cfg/cfg_fast.py", line 1484, in _job_queue_empty
    self._process_unresolved_indirect_jumps()
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/cfg/cfg_base.py", line 2167, in _process_unresolved_indirect_jumps
    all_targets |= self._process_one_indirect_jump(jump)
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/cfg/cfg_base.py", line 2193, in _process_one_indirect_jump
    resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
  File "/home/xx/.local/lib/python3.5/site-packages/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py", line 70, in resolve
    max_level=3, base_state=self.base_state)
  File "/home/xx/.local/lib/python3.5/site-packages/angr/blade.py", line 62, in __init__
    self._backward_slice()
  File "/home/xx/.local/lib/python3.5/site-packages/angr/blade.py", line 275, in _backward_slice
    data.get('stmt_idx', None)
  File "/home/xx/.local/lib/python3.5/site-packages/angr/blade.py", line 297, in _backward_slice_recursive
    if type(exit_stmt.guard) is pyvex.IRExpr.RdTmp:
AttributeError: 'WrTmp' object has no attribute ['guard'
```
[od.zip](https://github.com/angr/angr-doc/files/3185144/od.zip)

)

**Comment by rhelmot** [comment] 2019-05-20 18:44
I looked into this, and could not reproduce the above issue (cfg generation succeeded with `auto_load_libs=False`), but with `auto_load_libs=True` the following happened. It's passing None into solver.eval, where the None comes from the state's temp list, indicating that the jumptable resolver has flagged as important a temp that the slicing has excluded.

```
BackendError                              Traceback (most recent call last)
~/angr/claripy/claripy/frontends/light_frontend.py in eval(self, e, n, extra_constraints, exact)
     39         try:
---> 40             return tuple(self._solver_backend.eval(e, n))
     41         except BackendError:

~/angr/claripy/claripy/backends/__init__.py in eval(self, expr, n, extra_constraints, solver, model_callback)
    496         return self._eval(
--> 497             self.convert(expr), n, extra_constraints=self.convert_list(extra_constraints),
    498             solver=solver, model_callback=model_callback

~/angr/claripy/claripy/backends/backend_vsa.py in convert(self, expr)
    101     def convert(self, expr):
--> 102         return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
    103

~/angr/claripy/claripy/backends/__init__.py in convert(self, expr)
    159                     if type(ast) in {bool, int, str, float} or not isinstance(ast, Base):
--> 160                         converted = self._convert(ast)
    161                         arg_queue.append(converted)

~/angr/claripy/claripy/backends/backend_vsa.py in _convert(self, a)
    114         # Not supported
--> 115         raise BackendError()
    116

BackendError:

During handling of the above exception, another exception occurred:

ClaripyFrontendError                      Traceback (most recent call last)
~/angr/angr/angr/state_plugins/solver.py in wrapped_f(*args, **kwargs)
     86         try:
---> 87             return f(*args, **kwargs)
     88         except claripy.UnsatError as e:

~/angr/angr/angr/state_plugins/solver.py in _eval(self, e, n, extra_constraints, exact)
    498         """
--> 499         return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
    500

~/angr/claripy/claripy/frontend_mixins/concrete_handler_mixin.py in eval(self, e, n, **kwargs)
      6         else:
----> 7             return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
      8

~/angr/claripy/claripy/frontend_mixins/constraint_filter_mixin.py in eval(self, e, n, extra_constraints, **kwargs)
     39         ec = self._constraint_filter(extra_constraints)
---> 40         return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
     41

~/angr/claripy/claripy/frontends/light_frontend.py in eval(self, e, n, extra_constraints, exact)
     41         except BackendError:
---> 42             raise ClaripyFrontendError("Light solver can't handle this eval().")
     43

ClaripyFrontendError: Light solver can't handle this eval().

The above exception was the direct cause of the following exception:

SimSolverModeError                        Traceback (most recent call last)
<ipython-input-5-e1ca49faf383> in <module>
----> 1 p.analyses.CFGFast(normalize=True)

~/angr/angr/angr/analyses/analysis.py in __call__(self, *args, **kwargs)
    107
    108         oself._show_progressbar = show_progressbar
--> 109         oself.__init__(*args, **kwargs)
    110         return oself
    111

~/angr/angr/angr/analyses/cfg/cfg_fast.py in __init__(self, binary, objects, regions, pickle_intermediate_results, symbols, function_prologues, resolve_indirect_jumps, force_segment, force_complete_scan, indirect_jump_target_limit, collect_data_references, extra_cross_references, normalize, start_at_entry, function_starts, extra_memory_regions, data_type_guessing_handlers, arch_options, indirect_jump_resolvers, base_state, exclude_sparse_regions, skip_specific_regions, heuristic_plt_resolving, detect_tail_calls, low_priority, cfb, model, start, end, **extra_arch_options)
    624
    625         # Start working!
--> 626         self._analyze()
    627
    628     def __getstate__(self):

~/angr/angr/angr/analyses/forward_analysis.py in _analyze(self)
    581             # An example is the CFG recovery.
    582
--> 583             self._analysis_core_baremetal()
    584
    585         else:

~/angr/angr/angr/analyses/forward_analysis.py in _analysis_core_baremetal(self)
    682
    683             if not self._job_info_queue:
--> 684                 self._job_queue_empty()
    685
    686             if not self._job_info_queue:

~/angr/angr/angr/analyses/cfg/cfg_fast.py in _job_queue_empty(self)
   1104         # Try to see if there is any indirect jump left to be resolved
   1105         if self._resolve_indirect_jumps and self._indirect_jumps_to_resolve:
-> 1106             self._process_unresolved_indirect_jumps()
   1107
   1108             if self._job_info_queue:

~/angr/angr/angr/analyses/cfg/cfg_base.py in _process_unresolved_indirect_jumps(self)
   2141             if self._low_priority:
   2142                 self._release_gil(idx, 20, 0.0001)
-> 2143             all_targets |= self._process_one_indirect_jump(jump)
   2144
   2145         self._indirect_jumps_to_resolve.clear()

~/angr/angr/angr/analyses/cfg/cfg_base.py in _process_one_indirect_jump(self, jump)
   2167                 continue
   2168
-> 2169             resolved, targets = resolver.resolve(self, jump.addr, jump.func_addr, block, jump.jumpkind)
   2170             if resolved:
   2171                 resolved_by = resolver

~/angr/angr/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py in resolve(self, cfg, addr, func_addr, block, jumpkind)
    435                             jump_base_addr.tmp, jump_base_addr.tmp_1 = jump_base_addr.tmp_1, jump_base_addr.tmp
    436                         # Load the concrete base address
--> 437                         jump_base_addr.base_addr = state.solver.eval(state.scratch.temps[jump_base_addr.tmp_1])
    438
    439                 all_targets = [ ]

~/angr/angr/angr/state_plugins/solver.py in eval(self, e, **kwargs)
    722         """
    723         # eval_upto already throws the UnsatError, no reason for us to worry about it
--> 724         return self.eval_upto(e, 1, **kwargs)[0]
    725
    726     def eval_one(self, e, **kwargs):

~/angr/angr/angr/state_plugins/solver.py in eval_upto(self, e, n, cast_to, **kwargs)
    705             return [self._cast_to(e, concrete_val, cast_to)]
    706
--> 707         cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
    708         if len(cast_vals) == 0:
    709             raise SimUnsatError('Not satisfiable: %s, expected up to %d solutions' % (e.shallow_repr(), n))

~/angr/angr/angr/state_plugins/solver.py in concrete_shortcut_tuple(self, *args, **kwargs)
    152         v = _concrete_value(args[0])
    153         if v is None:
--> 154             return f(self, *args, **kwargs)
    155         else:
    156             return ( v, )

~/angr/angr/angr/state_plugins/sim_action_object.py in ast_stripper(*args, **kwargs)
     55         new_args = _raw_ast(args)
     56         new_kwargs = _raw_ast(kwargs)
---> 57         return f(*new_args, **new_kwargs)
     58     return ast_stripper
     59

~/angr/angr/angr/state_plugins/solver.py in wrapped_f(*args, **kwargs)
     89             raise SimUnsatError("Got an unsat result") from e
     90         except claripy.ClaripyFrontendError as e:
---> 91             raise SimSolverModeError("Claripy threw an error") from e
     92     return wrapped_f
     93

SimSolverModeError: Claripy threw an error
```

**Comment by ltfish** [comment] 2019-05-20 19:01
@taozi-xx  The original error that you reported in your issue has been fixed in angr master. Switching to the GitHub version of angr will solve your problem.

**Comment by rhelmot** [comment] 2019-05-24 01:30
The original bug report is resolved and I'm pretty sure my followup is a duplicate of angr/angr#1579 so I'm gonna close this

**Closed by rhelmot** 2019-05-24 01:30 UTC
Labels: bug
