### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by findream** [angr/angr-doc#205] opened 2018-08-30 09:40 UTC
Hello, when I was using angr, I had trouble executing the following code, which made me have a headache all the time. What should I do about it?
This is the code for execution.
```
# -*- coding:utf-8 -*-
import angr
import sys
import claripy
reload(sys)
sys.setdefaultencoding('utf8')
p = angr.Project('./ppp')           # 创建项目
state = p.factory.entry_state()     # 描述程序状态
for _ in xrange(4):                 # 获取4位标准输入
	  k = state.posix.files[0].read_from(1)  # 固定读取标准输入最后一个字节
	  state.se.add(k>47)            # 限制输入内容
k = state.posix.files[0].read_from(1)     # 读取最后一位
state.se.add(k==10)                 # k==10，换行符表示结束输入
state.posix.files[0].seek(0)        # 设置读取位置位起始位置
state.posix.files[0].length = 5     # 读取5位
print '[*] simulation_manager start...............'
# sm = p.factory.simulation_manager(state)
sm = p.factory.simgr(state)
sm.explore(find=0x08048689,avoid=0x0804869E)
if len(sm.found)>0:      # 获取到了found
	inp = sm.found[0].posix.files[0].all_bytes()   # 输出
	print sm.found[0].solver.eval(inp,cast_to = str)
print '[*] end angr.....'
```
This is a mistake.
```
Traceback (most recent call last):
  File "solve.py", line 54, in <module>
    print main()
  File "solve.py", line 23, in main
    k = st.posix.files[0].read_from(1)
AttributeError: 'SimSystemPosix' object has no attribute 'files'
```
In the same environment, using angr to run examples of your team, the result is the same mistake. This example iswyvern
Thanks very much

**Comment by rhelmot** [comment] 2018-08-30 09:41
Duplicate of https://github.com/angr/angr/issues/1186

**Closed by rhelmot** 2018-08-30 09:41 UTC
